title: "Footnotes"
url: https://toriocrema.github.io/footnotes
website: https://toriocrema.github.io
basewebsite: /footnotes
permalink: /:categories/:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"